import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const manifest=JSON.parse(await readFile('dist/release.json','utf8'));
if(manifest.games.length!==8)throw Error('Incomplete distribution. Run npm run build.');
await mkdir('releases',{recursive:true});
const archive=`armor-arcade-${manifest.version}.tar.gz`;
const result=spawnSync('tar',['--sort=name','--mtime=@0','--owner=0','--group=0','--numeric-owner','-czf',`releases/${archive}`,'-C','dist','.'],{stdio:'inherit'});
if(result.status!==0)process.exit(result.status??1);
const digest=createHash('sha256').update(await readFile(`releases/${archive}`)).digest('hex');
await writeFile(`releases/${archive}.sha256`,`${digest}  ${archive}\n`);
console.log(`Codex release: releases/${archive}\nSHA-256: ${digest}`);
